### PR TITLE
add "plagiarism" section

### PR DESCRIPTION
**Pull request by martin-martin**
I've encountered simple copy+paste of Andy's code. Reading the instructions here, a Reviewer who isn't familiar with that code might pass the submission:

> As long as the student submits some notes in HTML, the project will pass. 

Since I think this would miss the point, I've added two sentences regarding copy+paste issues.

---

I also deleted a stray word: "Criteria"

### CODE REVIEW

**Comment by morosebose** [comment]
Hey @martin-martin, thanks for this. Can you do me a favor and make the (grammatical) number consistent across the three bullet points? The first one has "the student" (singular), and the second, which you added, has "students" (plural), as does the third. If you can change the first to be plural as well, it would be great.

**Comment by martin-martin** [comment]
Hello Surajit!
This was more tricky than expected ; )

Do you think it's okay like this:

As long as students submit some notes in HTML, the project will pass. If a
> student submitted nothing, please mark the project as “Ungradable” and type
> in a message to the student outlining why the project is ungradable.


It feels somehow strange to put also that second sentence into plural,
since one is dealing this always on an individual basis. (I changed "the"
to "a" to make this more clear).

Is this fine or should I try to restructure it more?

: )
Martin

.

**Comment by morosebose** [comment]
Here you go, @martin-martin. Please change the file again with the language and I'll happily merge the pull request :-)

 > As long as the student submits some notes in HTML, the project meets specifications. If a student has submitted nothing, please mark the project as “Cannot Review” and type in a message to the student outlining why the project cannot be reviewed.
>
>  +If a student just copies [Andy's Code Example](https://classroom.udacity.com/nanodegrees/nd000/parts/0001345401/modules/385165862675461/lessons/3851658626239847/concepts/38473885480923), please mark the project as "Cannot Review" too. Take a moment to explain how, in order to learn, it is important to write your own code.  Also refer the student to the Udacity Honor Code. Remember that the student is new to the ND and to coding in general, so this is most probably not an attempt of plagiarism, but only a misunderstanding.
>   
>   The reviewer should comment and give at least 3 comments on students’ code. One of the comments needs to be a nitpick that guides students on best practices for HTML coding.
>

**Comment by martin-martin** [comment]
Re-read and adjusted : )

I also realized two more things:

1) the + probably came from github and sneaked its way in here? (I left it
in, because I considered it an addition to the previous paragraph, in terms
of "and also") - but I can remove.

2) I couldn't actually find the link to the Honor Code (because of the new
page?). Otherwise I'd have added a link here, too.

I just checked, and it's also not accessible through the project
submission, maybe that could be updated:

[image: Inline image 1]

(clicking anywhere just checks the box)

---

: )
I actually have quite some fun editing texts!

Have a good day!
Martin

.

**Comment by morosebose** [comment]
@martin-martin please remove the +, it is a typo I guess.

Link to the Honor Code is here: https://docs.google.com/document/d/1W-GV7Y0TNIPLox1UJDgFxvioq6Y0dYitQ-1_SIJsw0A/pub?embedded=true#h.6fabosc4oduo

I can't see the image you provided, for some reason. So I'm not sure what "it's also not accessible through the project submission" means. Is that relevant to to this pull request? If it's unrelated, could you please send an email to reviews-support@udacity.com about the issue?

Thanks!

**Comment by martin-martin** [comment]
Okay, great!

Changes made, thanks for the reply.

And I'll send the thing about the Honor code to support.

Have a good evening!
Martin

.

**Comment by morosebose** [comment]
Finally got around to merging this. Thanks @martin-martin!

**Comment by martin-martin** [comment]
Great! Thanks to you for the discussion and the improvements : )

.

**Pull request merged**
